/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestbank;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;


/**
 *
 * @author root
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    String poste;
     Connexion conn = new Connexion();
    Statement stat;
    ResultSet resp;
    DefaultTableModel model = new DefaultTableModel();
    public Client() {
        initComponents();
        this.jPanel_Client.setVisible(true);
        this.jPanel_GererClient.setVisible(false);
        this.jPanel_Liste_Client.setVisible(false);
        this.jPanel_NouveauClient.setVisible(false);
        
        
            
        model.addColumn("ID Client");
        model.addColumn("Nom et Prénoms");
        model.addColumn("Numero");
        model.addColumn("Adresse");
        model.addColumn("Sexe");
         try {

                String requete = "select *  from CLIENT";
                stat = conn.ObtenirConnexion().createStatement();
                resp = stat.executeQuery(requete);
                while (resp.next()) {
                   model.addRow(new Object[]{resp.getString("Id_client"), resp.getString("Nom_client"), resp.getString("Num_client"),resp.getString("Adresse"),resp.getString("Sexe")});
                }
            } catch (Exception e) {
                System.err.println(e);

            }
            jTable_Client.setModel(model);
        
    }

    public Client(String Poste) {
        initComponents();
        poste=Poste;
        this.jPanel_Client.setVisible(true);
        this.jPanel_GererClient.setVisible(false);
        this.jPanel_Liste_Client.setVisible(false);
        this.jPanel_NouveauClient.setVisible(false);
        
        
            
        model.addColumn("ID Client");
        model.addColumn("Nom et Prénoms");
        model.addColumn("Numero");
        model.addColumn("Adresse");
        model.addColumn("Sexe");
         try {

                String requete = "select *  from CLIENT";
                stat = conn.ObtenirConnexion().createStatement();
                resp = stat.executeQuery(requete);
                while (resp.next()) {
                   model.addRow(new Object[]{resp.getString("Id_client"), resp.getString("Nom_client"), resp.getString("Num_client"),resp.getString("Adresse"),resp.getString("Sexe")});
                }
            } catch (Exception e) {
                System.err.println(e);

            }
            jTable_Client.setModel(model);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Client = new javax.swing.JPanel();
        jButton_Nouveau = new javax.swing.JButton();
        jButton_Gerer = new javax.swing.JButton();
        jButton_Retour = new javax.swing.JButton();
        jButton_liste = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_NouveauClient = new javax.swing.JPanel();
        jButton_Retour1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCombo_Sexe = new javax.swing.JComboBox();
        adresse_client = new javax.swing.JTextField();
        numero_client = new javax.swing.JTextField();
        nom_client = new javax.swing.JTextField();
        jButton_annuler = new javax.swing.JButton();
        jButton_Ajouter_Client = new javax.swing.JButton();
        jPanel_GererClient = new javax.swing.JPanel();
        jButton_Retour2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCombo_Sexe_gest = new javax.swing.JComboBox();
        adresse_client_gest = new javax.swing.JTextField();
        numero_client_gest = new javax.swing.JTextField();
        nom_client_gest = new javax.swing.JTextField();
        jButton_rechercher = new javax.swing.JButton();
        jButton_Modifier_Client = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ID_client = new javax.swing.JTextField();
        jPanel_Liste_Client = new javax.swing.JPanel();
        jButton_Retour3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Client = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Client.setBackground(java.awt.Color.white);

        jButton_Nouveau.setText("NOUVEAU");
        jButton_Nouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NouveauActionPerformed(evt);
            }
        });

        jButton_Gerer.setText("GERER");
        jButton_Gerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GererActionPerformed(evt);
            }
        });

        jButton_Retour.setText("RETOUR");
        jButton_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RetourActionPerformed(evt);
            }
        });

        jButton_liste.setText("LISTE");
        jButton_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_listeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ClientLayout = new javax.swing.GroupLayout(jPanel_Client);
        jPanel_Client.setLayout(jPanel_ClientLayout);
        jPanel_ClientLayout.setHorizontalGroup(
            jPanel_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClientLayout.createSequentialGroup()
                .addGroup(jPanel_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ClientLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_ClientLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton_Nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton_Gerer, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_ClientLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jButton_liste, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ClientLayout.setVerticalGroup(
            jPanel_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ClientLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Nouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Gerer, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton_liste, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Amiri", 1, 24)); // NOI18N
        jLabel1.setText("CLIENT");

        jPanel_NouveauClient.setBackground(java.awt.Color.white);

        jButton_Retour1.setText("RETOUR");
        jButton_Retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom Prénoms");

        jLabel3.setText("Numéro de Téléphone");

        jLabel4.setText("Adresse");

        jLabel5.setText("Sexe");

        jCombo_Sexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexe", "Masculin", "Feminin" }));

        jButton_annuler.setText("ANNULER");
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        jButton_Ajouter_Client.setText("VALIDER");
        jButton_Ajouter_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ajouter_ClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NouveauClientLayout = new javax.swing.GroupLayout(jPanel_NouveauClient);
        jPanel_NouveauClient.setLayout(jPanel_NouveauClientLayout);
        jPanel_NouveauClientLayout.setHorizontalGroup(
            jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NouveauClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombo_Sexe, 0, 260, Short.MAX_VALUE)
                    .addComponent(adresse_client)
                    .addComponent(numero_client)
                    .addComponent(nom_client))
                .addGap(63, 63, 63)
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Retour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jButton_Ajouter_Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_NouveauClientLayout.setVerticalGroup(
            jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NouveauClientLayout.createSequentialGroup()
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NouveauClientLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_NouveauClientLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero_client, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NouveauClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NouveauClientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Ajouter_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_NouveauClientLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adresse_client, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_NouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombo_Sexe, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton_Retour1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_GererClient.setBackground(java.awt.Color.white);

        jButton_Retour2.setText("RETOUR");
        jButton_Retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nom Prénoms");

        jLabel7.setText("Numéro de Téléphone");

        jLabel8.setText("Adresse");

        jLabel9.setText("Sexe");

        jCombo_Sexe_gest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexe", "Masculin", "Feminin" }));

        jButton_rechercher.setText("RECHERCHER");
        jButton_rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rechercherActionPerformed(evt);
            }
        });

        jButton_Modifier_Client.setText("MODIFIER");
        jButton_Modifier_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modifier_ClientActionPerformed(evt);
            }
        });

        jLabel11.setText("ID Client");

        javax.swing.GroupLayout jPanel_GererClientLayout = new javax.swing.GroupLayout(jPanel_GererClient);
        jPanel_GererClient.setLayout(jPanel_GererClientLayout);
        jPanel_GererClientLayout.setHorizontalGroup(
            jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GererClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombo_Sexe_gest, 0, 260, Short.MAX_VALUE)
                    .addComponent(adresse_client_gest)
                    .addComponent(numero_client_gest)
                    .addComponent(nom_client_gest)
                    .addComponent(ID_client))
                .addGap(63, 63, 63)
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Retour2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jButton_Modifier_Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_GererClientLayout.setVerticalGroup(
            jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GererClientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_client, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GererClientLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GererClientLayout.createSequentialGroup()
                        .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nom_client_gest)
                            .addComponent(jButton_rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_GererClientLayout.createSequentialGroup()
                        .addComponent(jButton_Modifier_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_GererClientLayout.createSequentialGroup()
                        .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero_client_gest, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adresse_client_gest, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GererClientLayout.createSequentialGroup()
                        .addComponent(jButton_Retour2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_GererClientLayout.createSequentialGroup()
                        .addGroup(jPanel_GererClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCombo_Sexe_gest, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        jPanel_Liste_Client.setBackground(java.awt.Color.white);

        jButton_Retour3.setText("RETOUR");
        jButton_Retour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour3ActionPerformed(evt);
            }
        });

        jTable_Client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Client", "Nom Prenoms", "Numero Telephone", "Adresse", "Sexe"
            }
        ));
        jScrollPane1.setViewportView(jTable_Client);

        javax.swing.GroupLayout jPanel_Liste_ClientLayout = new javax.swing.GroupLayout(jPanel_Liste_Client);
        jPanel_Liste_Client.setLayout(jPanel_Liste_ClientLayout);
        jPanel_Liste_ClientLayout.setHorizontalGroup(
            jPanel_Liste_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Liste_ClientLayout.createSequentialGroup()
                .addGap(509, 509, 509)
                .addComponent(jButton_Retour3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel_Liste_ClientLayout.setVerticalGroup(
            jPanel_Liste_ClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Liste_ClientLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Retour3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_NouveauClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_GererClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Liste_Client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(82, Short.MAX_VALUE)
                    .addComponent(jPanel_NouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_GererClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Liste_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GererActionPerformed
        // TODO add your handling code here:
          this.jPanel_Client.setVisible(false);
          this.jPanel_GererClient.setVisible(true);
    }//GEN-LAST:event_jButton_GererActionPerformed

    private void jButton_NouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NouveauActionPerformed
        // TODO add your handling code here:
        this.jPanel_Client.setVisible(false);
        this.jPanel_NouveauClient.setVisible(true);
    }//GEN-LAST:event_jButton_NouveauActionPerformed

    private void jButton_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_listeActionPerformed
        // TODO add your handling code here:
          this.jPanel_Client.setVisible(false);
          this.jPanel_Liste_Client.setVisible(true);
    }//GEN-LAST:event_jButton_listeActionPerformed

    private void jButton_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RetourActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(poste);
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton_RetourActionPerformed

    private void jButton_Ajouter_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ajouter_ClientActionPerformed
        // TODO add your handling code here:
        
         if (jCombo_Sexe.getSelectedItem().toString()=="Sexe" || nom_client.getText().isEmpty() || numero_client.getText().isEmpty()|| adresse_client.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "veuillez remplir tous les champs");
        } else {
            
                        
            String Sexe = jCombo_Sexe.getSelectedItem().toString();
            String numero = numero_client.getText();
            String name = nom_client.getText();
            String adresse = adresse_client.getText();
            

            String requet = "insert into CLIENT ('Nom_client', 'Num_client', 'Adresse', 'Sexe') values( '" + name + "','"+ numero +"','"+ adresse +"','"+ Sexe +"')";
            try {
                stat = conn.ObtenirConnexion().createStatement();
                stat.executeUpdate(requet);
                //vide tous les champs apres le insert
             
                adresse_client.setText(" ");
                numero_client.setText("");
                nom_client.setText("");
                jCombo_Sexe.setSelectedItem("Sexe");
                JOptionPane.showMessageDialog(null, " enregistré avec succes ");
                //actualise la table apres le insert
                model.setRowCount(0);
                String requete = ("select Id_client, Nom_client, Num_client, Adresse, Sexe from CLIENT");
                resp = stat.executeQuery(requete);
                ResultSetMetaData metadata = resp.getMetaData();
                while (resp.next()) {
                   model.addRow(new Object[]{resp.getString("Id_client"), resp.getString("Nom_client"), resp.getString("Num_client"),resp.getString("Adresse"),resp.getString("Sexe")});

                }
                jTable_Client.setModel(model);
            } catch (SQLException ex) {
                System.out.println(ex);
            } finally{

                try {
                    stat.close();
                    resp.close();

                }catch (Exception e){ }
            }
        
        }
        
        
    }//GEN-LAST:event_jButton_Ajouter_ClientActionPerformed

    private void jButton_Retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour1ActionPerformed
        // TODO add your handling code here:
        this.jPanel_NouveauClient.setVisible(false);
        this.jPanel_Client.setVisible(true);
    }//GEN-LAST:event_jButton_Retour1ActionPerformed

    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
        // TODO add your handling code here:
                adresse_client.setText(" ");
                numero_client.setText("");
                nom_client.setText("");
                jCombo_Sexe.setSelectedItem("Sexe");
    }//GEN-LAST:event_jButton_annulerActionPerformed

    private void jButton_Retour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour3ActionPerformed
        // TODO add your handling code here:
        this.jPanel_Liste_Client.setVisible(false);
        this.jPanel_Client.setVisible(true);
    }//GEN-LAST:event_jButton_Retour3ActionPerformed

    private void jButton_Retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour2ActionPerformed
        // TODO add your handling code here:
        this.jPanel_GererClient.setVisible(false);
        this.jPanel_Client.setVisible(true);
    }//GEN-LAST:event_jButton_Retour2ActionPerformed

    private void jButton_rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rechercherActionPerformed
         try {
             // TODO add your handling code here:
             int ID = Integer.parseInt(ID_client.getText());
             String name= nom_client.getText();
             String req = "select Id_client, Nom_client, Num_client, Adresse, Sexe from CLIENT where (Id_client="+ID+" or Nom_client='"+name+"')";
             resp = stat.executeQuery(req);
             ResultSetMetaData metadata = resp.getMetaData();
              while (resp.next()) {
                  
                  nom_client_gest.setText(resp.getString("Nom_client"));
                  numero_client_gest.setText(resp.getString("Num_client"));
                  adresse_client_gest.setText(resp.getString("Adresse"));
                  jCombo_Sexe_gest.setSelectedItem(resp.getString("Sexe"));
                  

                 

                }
             
         } catch (SQLException ex) {
             Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton_rechercherActionPerformed

    private void jButton_Modifier_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modifier_ClientActionPerformed
        // TODO add your handling code here:
        
         if (ID_client.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez choisir id  et entrer les information à modifier");
        } else {
            try {
                if (JOptionPane.showConfirmDialog(null, "Confirmer la modification", "modification", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    stat.executeUpdate("update CLIENT set Nom_client='" + nom_client_gest.getText() + "',Num_client='"+numero_client_gest.getText()+"', Adresse='"+adresse_client_gest.getText()+"', Sexe='"+jCombo_Sexe_gest.getSelectedItem()+"'"
                        + "where Id_client='" + ID_client.getText() + "'");
                    //vide les champs apres update
                    ID_client.setText(" ");
                    nom_client_gest.setText(" ");
                    numero_client_gest.setText(" ");
                    adresse_client_gest.setText("");
                    jCombo_Sexe_gest.setSelectedItem("Sexe");
                   

                    model.setRowCount(0);
                    String requete = "select *from CLIENT";
                    stat = conn.ObtenirConnexion().createStatement();
                    resp = stat.executeQuery(requete);
                    ResultSetMetaData metadata = resp.getMetaData();
                    while (resp.next()) {
                        model.addRow(new Object[]{resp.getString("Id_client"), resp.getString("Nom_client"), resp.getString("Num_client"),resp.getString("Adresse"),resp.getString("Sexe")});
}

                JOptionPane.showMessageDialog(null, "Modification réussie");
            }
                jTable_Client.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !!!! " + e.getMessage());
            System.out.println(e);
        }finally{ 
            
                try {
                    stat.close();
                    resp.close();
                    
                }catch (Exception e){ }
            }
         }
    }//GEN-LAST:event_jButton_Modifier_ClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_client;
    private javax.swing.JTextField adresse_client;
    private javax.swing.JTextField adresse_client_gest;
    private javax.swing.JButton jButton_Ajouter_Client;
    private javax.swing.JButton jButton_Gerer;
    private javax.swing.JButton jButton_Modifier_Client;
    private javax.swing.JButton jButton_Nouveau;
    private javax.swing.JButton jButton_Retour;
    private javax.swing.JButton jButton_Retour1;
    private javax.swing.JButton jButton_Retour2;
    private javax.swing.JButton jButton_Retour3;
    private javax.swing.JButton jButton_annuler;
    private javax.swing.JButton jButton_liste;
    private javax.swing.JButton jButton_rechercher;
    private javax.swing.JComboBox jCombo_Sexe;
    private javax.swing.JComboBox jCombo_Sexe_gest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_Client;
    private javax.swing.JPanel jPanel_GererClient;
    private javax.swing.JPanel jPanel_Liste_Client;
    private javax.swing.JPanel jPanel_NouveauClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Client;
    private javax.swing.JTextField nom_client;
    private javax.swing.JTextField nom_client_gest;
    private javax.swing.JTextField numero_client;
    private javax.swing.JTextField numero_client_gest;
    // End of variables declaration//GEN-END:variables
}
