/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestbank;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLEncoder;


/**
 *
 * @author root
 */
public final class Compte extends javax.swing.JFrame {

    /**
     * Creates new form Compte
     */
    String poste;
    Connexion conn = new Connexion();
    Statement stat;
    ResultSet resp;
    DefaultTableModel model = new DefaultTableModel(), tableau=new DefaultTableModel();
    public Compte() {
        initComponents();
        this.jPanel_compte.setVisible(true);
        this.jPanel_Liste.setVisible(false);
        this.jPanel_NouveauCompte.setVisible(false);
        this.jPanel_Gestion_compte.setVisible(false);
        this.jPanel_Releve.setVisible(false);
        
        
        
        model.addColumn("Numero Compte");
        model.addColumn("Code Client");
        model.addColumn("Intitulé");
        model.addColumn("Type");
        model.addColumn("Solde");
        model.addColumn("Taux interet");
        
        
        
        tableau.addColumn("ID Transaction");
        tableau.addColumn("Type");
        tableau.addColumn("Date");
        tableau.addColumn("Montant");
        tableau.addColumn("Source");
        tableau.addColumn("Destination");
        
        
          try {

                String requete = "select *  from COMPTE";
                stat = conn.ObtenirConnexion().createStatement();
                resp = stat.executeQuery(requete);
                while (resp.next()) {
                  model.addRow(new Object[]{resp.getString("Num_compte"), resp.getString("Code_client"), resp.getString("Intitule_compte"),resp.getString("Type_compte"),resp.getString("Solde_compte"),resp.getString("Taux_interet")});
                }
            } catch (Exception e) {
                System.err.println(e);

            }
            jTable_Compte.setModel(model);
        
        fillCombo();
        
    }
    
    public Compte(String Poste) {
        initComponents();
        poste=Poste;
        this.jPanel_compte.setVisible(true);
        this.jPanel_Liste.setVisible(false);
        this.jPanel_NouveauCompte.setVisible(false);
        this.jPanel_Gestion_compte.setVisible(false);
        this.jPanel_Releve.setVisible(false);
        
        
        
        model.addColumn("Numero Compte");
        model.addColumn("Code Client");
        model.addColumn("Intitulé");
        model.addColumn("Type");
        model.addColumn("Solde");
        model.addColumn("Taux interet");
        
        
        
        tableau.addColumn("ID Transaction");
        tableau.addColumn("Type");
        tableau.addColumn("Date");
        tableau.addColumn("Montant");
        tableau.addColumn("Source");
        tableau.addColumn("Destination");
        
        
          try {

                String requete = "select *  from COMPTE";
                stat = conn.ObtenirConnexion().createStatement();
                resp = stat.executeQuery(requete);
                while (resp.next()) {
                  model.addRow(new Object[]{resp.getString("Num_compte"), resp.getString("Code_client"), resp.getString("Intitule_compte"),resp.getString("Type_compte"),resp.getString("Solde_compte"),resp.getString("Taux_interet")});
                }
            } catch (Exception e) {
                System.err.println(e);

            }
            jTable_Compte.setModel(model);
        
        fillCombo();
        
    }
    
    
    public void fillCombo(){
        String sql = "select Id_client from CLIENT";
        try {
            stat=conn.ObtenirConnexion().createStatement();
            resp=stat.executeQuery(sql);
              ResultSetMetaData metadata = resp.getMetaData();
              while (resp.next()) {
                  jComboClient.addItem(resp.getString("Id_client"));
                 
                }
        } catch (SQLException ex) {
            Logger.getLogger(Compte.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_compte = new javax.swing.JPanel();
        jButton_Creation = new javax.swing.JButton();
        jButton_Gestion = new javax.swing.JButton();
        jButton_Liste = new javax.swing.JButton();
        jButton_Retour = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Liste = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Compte = new javax.swing.JTable();
        jButton_Retour_compte = new javax.swing.JButton();
        jPanel_NouveauCompte = new javax.swing.JPanel();
        jButton_Retour1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        decouvert_autorise = new javax.swing.JTextField();
        nom_client = new javax.swing.JTextField();
        jButton_annuler = new javax.swing.JButton();
        jButton_Ajouter_Compte = new javax.swing.JButton();
        jComboClient = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jCombo_Typecompte = new javax.swing.JComboBox();
        depot_initial = new javax.swing.JTextField();
        jPanel_Gestion_compte = new javax.swing.JPanel();
        jButton_Retour2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        decouvert_autorise1 = new javax.swing.JTextField();
        num_compte = new javax.swing.JTextField();
        jButton_annuler1 = new javax.swing.JButton();
        jButton_Modifier_compte = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCombo_Typecompte1 = new javax.swing.JComboBox();
        intitule_compte_gest = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        solde_compte_gest = new javax.swing.JTextField();
        Rechercher = new javax.swing.JButton();
        taux_inter = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        client = new javax.swing.JTextField();
        jPanel_Releve = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Numero_compte = new javax.swing.JTextField();
        Valider_releve = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Compte_releve = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_compte.setBackground(java.awt.Color.white);

        jButton_Creation.setText("CREATION");
        jButton_Creation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreationActionPerformed(evt);
            }
        });

        jButton_Gestion.setText("GESTION");
        jButton_Gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionActionPerformed(evt);
            }
        });

        jButton_Liste.setText("LISTE COMPTE");
        jButton_Liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListeActionPerformed(evt);
            }
        });

        jButton_Retour.setText("RETOUR");
        jButton_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RetourActionPerformed(evt);
            }
        });

        jButton1.setText("RELEVE COMPTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_compteLayout = new javax.swing.GroupLayout(jPanel_compte);
        jPanel_compte.setLayout(jPanel_compteLayout);
        jPanel_compteLayout.setHorizontalGroup(
            jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_compteLayout.createSequentialGroup()
                .addGroup(jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_compteLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Creation, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Liste, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Gestion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_compteLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jButton_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel_compteLayout.setVerticalGroup(
            jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_compteLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Creation, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Gestion, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Liste, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        jLabel1.setFont(new java.awt.Font("Amiri", 1, 24)); // NOI18N
        jLabel1.setText("COMPTE");

        jPanel_Liste.setBackground(java.awt.Color.white);

        jTable_Compte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Compte", "Code Client", "Intitulé", "Type", "Solde", "Taux Intérêt"
            }
        ));
        jScrollPane1.setViewportView(jTable_Compte);

        jButton_Retour_compte.setText("Retour");
        jButton_Retour_compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour_compteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ListeLayout = new javax.swing.GroupLayout(jPanel_Liste);
        jPanel_Liste.setLayout(jPanel_ListeLayout);
        jPanel_ListeLayout.setHorizontalGroup(
            jPanel_ListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ListeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_ListeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Retour_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ListeLayout.setVerticalGroup(
            jPanel_ListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ListeLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_Retour_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_NouveauCompte.setBackground(java.awt.Color.white);

        jButton_Retour1.setText("RETOUR");
        jButton_Retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Intitulé");

        jLabel3.setText("Client");

        jLabel4.setText("Découvert autorisé");

        jLabel5.setText("Dépot Initial");

        jButton_annuler.setText("ANNULER");
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        jButton_Ajouter_Compte.setText("VALIDER");
        jButton_Ajouter_Compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Ajouter_CompteActionPerformed(evt);
            }
        });

        jLabel6.setText("Type");

        jCombo_Typecompte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Epargne", "Courant", "Entreprise" }));

        javax.swing.GroupLayout jPanel_NouveauCompteLayout = new javax.swing.GroupLayout(jPanel_NouveauCompte);
        jPanel_NouveauCompte.setLayout(jPanel_NouveauCompteLayout);
        jPanel_NouveauCompteLayout.setHorizontalGroup(
            jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NouveauCompteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(decouvert_autorise)
                    .addComponent(nom_client)
                    .addComponent(jComboClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCombo_Typecompte, 0, 260, Short.MAX_VALUE)
                    .addComponent(depot_initial))
                .addGap(63, 63, 63)
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Retour1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_annuler, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jButton_Ajouter_Compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_NouveauCompteLayout.setVerticalGroup(
            jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NouveauCompteLayout.createSequentialGroup()
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NouveauCompteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_NouveauCompteLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(nom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboClient, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NouveauCompteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Ajouter_Compte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCombo_Typecompte, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depot_initial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_NouveauCompteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Retour1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_NouveauCompteLayout.createSequentialGroup()
                        .addGroup(jPanel_NouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decouvert_autorise, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel_Gestion_compte.setBackground(java.awt.Color.white);

        jButton_Retour2.setText("RETOUR");
        jButton_Retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Retour2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Numero de Compte");

        jLabel8.setText("Client");

        jLabel9.setText("Découvert autorisé");

        jLabel10.setText("Intitulé de Compte");

        jButton_annuler1.setText("ANNULER");
        jButton_annuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annuler1ActionPerformed(evt);
            }
        });

        jButton_Modifier_compte.setText("MODIFIER");
        jButton_Modifier_compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Modifier_compteActionPerformed(evt);
            }
        });

        jLabel11.setText("Type");

        jCombo_Typecompte1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Epargne", "Courant", "Entreprise" }));

        jLabel12.setText("Solde du compte");

        Rechercher.setText("RECHERCHER");
        Rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechercherActionPerformed(evt);
            }
        });

        jLabel13.setText("Taux Interet");

        javax.swing.GroupLayout jPanel_Gestion_compteLayout = new javax.swing.GroupLayout(jPanel_Gestion_compte);
        jPanel_Gestion_compte.setLayout(jPanel_Gestion_compteLayout);
        jPanel_Gestion_compteLayout.setHorizontalGroup(
            jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taux_inter)
                    .addComponent(decouvert_autorise1)
                    .addComponent(num_compte)
                    .addComponent(jCombo_Typecompte1, 0, 260, Short.MAX_VALUE)
                    .addComponent(intitule_compte_gest)
                    .addComponent(solde_compte_gest)
                    .addComponent(client))
                .addGap(63, 63, 63)
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Retour2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_annuler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Modifier_compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Gestion_compteLayout.setVerticalGroup(
            jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Gestion_compteLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(num_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_annuler1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCombo_Typecompte1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intitule_compte_gest, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decouvert_autorise1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(solde_compte_gest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_Gestion_compteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Modifier_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel_Gestion_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Retour2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taux_inter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel_Releve.setBackground(java.awt.Color.white);

        jLabel14.setFont(new java.awt.Font("Go Mono", 1, 18)); // NOI18N
        jLabel14.setText("RELEVE DE COMPTE");

        jLabel15.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel15.setText("Numéro de Compte");

        Valider_releve.setText("Valider");
        Valider_releve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider_releveActionPerformed(evt);
            }
        });

        jTable_Compte_releve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero Compte", "Code Client", "Intitulé", "Type", "Solde", "Taux Intérêt"
            }
        ));
        jScrollPane2.setViewportView(jTable_Compte_releve);

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ReleveLayout = new javax.swing.GroupLayout(jPanel_Releve);
        jPanel_Releve.setLayout(jPanel_ReleveLayout);
        jPanel_ReleveLayout.setHorizontalGroup(
            jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReleveLayout.createSequentialGroup()
                .addGroup(jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ReleveLayout.createSequentialGroup()
                        .addGroup(jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_ReleveLayout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Numero_compte, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(Valider_releve, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_ReleveLayout.createSequentialGroup()
                                    .addGap(212, 212, 212)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ReleveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_ReleveLayout.setVerticalGroup(
            jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReleveLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel_ReleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Valider_releve, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero_compte))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_Liste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jPanel_NouveauCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(30, 30, 30)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Gestion_compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Releve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 71, Short.MAX_VALUE)
                    .addComponent(jPanel_Liste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jPanel_NouveauCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Gestion_compte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Releve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Retour_compteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour_compteActionPerformed
        // TODO add your handling code here:
        
        this.jPanel_Liste.setVisible(false);
        this.jPanel_compte.setVisible(true);
    }//GEN-LAST:event_jButton_Retour_compteActionPerformed

    private void jButton_CreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreationActionPerformed
        // TODO add your handling code here:
        this.jPanel_compte.setVisible(false);
        this.jPanel_NouveauCompte.setVisible(true);
    }//GEN-LAST:event_jButton_CreationActionPerformed

    private void jButton_Retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour1ActionPerformed
        // TODO add your handling code here:
        this.jPanel_NouveauCompte.setVisible(false);
        this.jPanel_compte.setVisible(true);
    }//GEN-LAST:event_jButton_Retour1ActionPerformed

    private void jButton_Retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Retour2ActionPerformed
        // TODO add your handling code here:
        this.jPanel_Gestion_compte.setVisible(false);
        this.jPanel_compte.setVisible(true);
    }//GEN-LAST:event_jButton_Retour2ActionPerformed

    private void jButton_annuler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annuler1ActionPerformed
        // TODO add your handling code here:
        num_compte.setText(" ");
        intitule_compte_gest.setText(" ");
        decouvert_autorise1.setText(" ");
        solde_compte_gest.setText(" ");
    }//GEN-LAST:event_jButton_annuler1ActionPerformed

    private void jButton_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu = new Menu(poste);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton_RetourActionPerformed

    private void jButton_ListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListeActionPerformed
        // TODO add your handling code here:
        this.jPanel_compte.setVisible(false);
        this.jPanel_Liste.setVisible(true);
    }//GEN-LAST:event_jButton_ListeActionPerformed

    private void jButton_GestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionActionPerformed
        // TODO add your handling code here:
         this.jPanel_compte.setVisible(false);
        this.jPanel_Gestion_compte.setVisible(true);        
    }//GEN-LAST:event_jButton_GestionActionPerformed

    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
        // TODO add your handling code here:
        nom_client.setText("");
        jComboClient.setSelectedItem("");
        jCombo_Typecompte.setSelectedItem("");
        depot_initial.setText("");
        decouvert_autorise.setText("0");
    }//GEN-LAST:event_jButton_annulerActionPerformed

    private void jButton_Ajouter_CompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Ajouter_CompteActionPerformed
        // TODO add your handling code here:
        
        float taux ;
         
         if (jComboClient.getSelectedItem().toString().isEmpty() || nom_client.getText().isEmpty() || depot_initial.getText().isEmpty()|| decouvert_autorise.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "veuillez remplir tous les champs");
        } else {
            
                        
            String Client = jComboClient.getSelectedItem().toString();
            String depot = depot_initial.getText();
            String name = nom_client.getText();
            int decouvert =Integer.parseInt(decouvert_autorise.getText());
            String type = jCombo_Typecompte.getSelectedItem().toString();
            
            if(type=="Epargne") {
                taux=2;
            }
            else{ taux=0;}
            
            

            String requet = "insert into COMPTE ('Code_client', 'Intitule_compte', 'Solde_compte', 'Taux_interet', 'Type_compte', 'Decouvert') values( '" + Client + "','"+ name +"','"+ depot +"',"+ taux +",'"+ type +"',"+ decouvert +")";
            try {
                stat = conn.ObtenirConnexion().createStatement();
                stat.executeUpdate(requet);
                //vide tous les champs apres le insert
                jComboClient.setSelectedItem("");
                depot_initial.setText(" ");
                decouvert_autorise.setText("");
                nom_client.setText("");
                jCombo_Typecompte.setSelectedItem("Epargne");
                JOptionPane.showMessageDialog(null, " enregistré avec succes ");
                //actualise la table apres le insert
                model.setRowCount(0);
                String requete = ("select * from COMPTE");
                resp = stat.executeQuery(requete);
                ResultSetMetaData metadata = resp.getMetaData();
                while (resp.next()) {
                   model.addRow(new Object[]{resp.getString("Num_compte"), resp.getString("Code_client"), resp.getString("Intitule_compte"),resp.getString("Type_compte"),resp.getString("Solde_compte"),resp.getString("Taux_interet")});

                }
                jTable_Compte.setModel(model);
            } catch (SQLException ex) {
                System.out.println(ex);
            } finally{

                try {
                    stat.close();
                    resp.close();

                }catch (Exception e){ }
            }
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton_Ajouter_CompteActionPerformed

    private void RechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechercherActionPerformed
        // TODO add your handling code here:
        
          try {
             // TODO add your handling code here:
             int ID = Integer.parseInt(num_compte.getText());
             
             String intitule= intitule_compte_gest.getText();
             if(num_compte.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null, " Veuillez remplir le champ du numéro de Compte ");
             }
             String req = "select * from COMPTE where (Num_compte="+ID+")";
             resp = stat.executeQuery(req);
             ResultSetMetaData metadata = resp.getMetaData();
              while (resp.next()) {
                  
                  intitule_compte_gest.setText(resp.getString("Intitule_compte"));
                  client.setText(resp.getString("Code_client"));
                  jCombo_Typecompte1.setSelectedItem(resp.getString("Type_compte"));
                  decouvert_autorise1.setText(resp.getString("Decouvert"));
                  solde_compte_gest.setText(resp.getString("Solde_compte"));
                  taux_inter.setText(resp.getString("Taux_interet"));
                                                
                

                }
             
         } catch (SQLException ex) {
             Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_RechercherActionPerformed

    private void jButton_Modifier_compteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Modifier_compteActionPerformed
        // TODO add your handling code here:
        
        if (num_compte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez Saisir le numéro de compte  et entrer les informations à modifier");
        } else {
            try {
                if (JOptionPane.showConfirmDialog(null, "Confirmer la modification", "modification", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    stat.executeUpdate("update COMPTE set Code_client='" + Integer.parseInt(client.getText()) + "',Intitule_compte='"+intitule_compte_gest.getText()+"', Solde_compte='"+solde_compte_gest.getText()+"', Taux_interet='"+taux_inter.getText()+"', Type_compte='"+jCombo_Typecompte1.getSelectedItem()+"' , Decouvert='"+decouvert_autorise1.getText()+"'"
                        + "where Num_compte='" + Integer.parseInt(num_compte.getText()) + "'");
                    //vide les champs apres update
                    num_compte.setText(" ");
                    client.setText(" ");
                    intitule_compte_gest.setText(" ");
                    solde_compte_gest.setText("");
                    taux_inter.setText("");
                    decouvert_autorise1.setText("");
                    jCombo_Typecompte.setSelectedItem(" ");
                    
                   

                    model.setRowCount(0);
                    String requete = "select *from COMPTE";
                    stat = conn.ObtenirConnexion().createStatement();
                    resp = stat.executeQuery(requete);
                    ResultSetMetaData metadata = resp.getMetaData();
                    while (resp.next()) {
                      model.addRow(new Object[]{resp.getString("Num_compte"), resp.getString("Code_client"), resp.getString("Intitule_compte"),resp.getString("Type_compte"),resp.getString("Solde_compte"),resp.getString("Taux_interet")});
}

                JOptionPane.showMessageDialog(null, "Modification réussie");
            }
                jTable_Compte.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "erreur de modification !!!! " + e.getMessage());
            System.out.println(e);
        }finally{ 
            
                try {
                    stat.close();
                    resp.close();
                    
                }catch (Exception e){ }
            }
         }
        
        
        
        
    }//GEN-LAST:event_jButton_Modifier_compteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jPanel_Releve.setVisible(false);
        this.jPanel_compte.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Valider_releveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider_releveActionPerformed
        // TODO add your handling code here:
        if (Numero_compte.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "veuillez remplir tous les champs");
        } 
        else {
        
            try{
                int num = Integer.parseInt(Numero_compte.getText());
                String req = "select * from Operations where (Source="+num+" or Destination="+num+")";
                stat=conn.ObtenirConnexion().createStatement();
                resp = stat.executeQuery(req);
                    ResultSetMetaData metadata = resp.getMetaData();
                    while (resp.next()) {
                      tableau.addRow(new Object[]{resp.getString("ID"), resp.getString("Type"), resp.getString("Date"),resp.getString("Montant"),resp.getString("Source"),resp.getString("Destination")});
           
                    }
                     jTable_Compte_releve.setModel(tableau);
            }catch (SQLException ex) {
                Logger.getLogger(Compte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        
        
        }
    }//GEN-LAST:event_Valider_releveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jPanel_compte.setVisible(false);
        this.jPanel_Releve.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Numero_compte;
    private javax.swing.JButton Rechercher;
    private javax.swing.JButton Valider_releve;
    private javax.swing.JTextField client;
    private javax.swing.JTextField decouvert_autorise;
    private javax.swing.JTextField decouvert_autorise1;
    private javax.swing.JTextField depot_initial;
    private javax.swing.JTextField intitule_compte_gest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Ajouter_Compte;
    private javax.swing.JButton jButton_Creation;
    private javax.swing.JButton jButton_Gestion;
    private javax.swing.JButton jButton_Liste;
    private javax.swing.JButton jButton_Modifier_compte;
    private javax.swing.JButton jButton_Retour;
    private javax.swing.JButton jButton_Retour1;
    private javax.swing.JButton jButton_Retour2;
    private javax.swing.JButton jButton_Retour_compte;
    private javax.swing.JButton jButton_annuler;
    private javax.swing.JButton jButton_annuler1;
    private javax.swing.JComboBox jComboClient;
    private javax.swing.JComboBox jCombo_Typecompte;
    private javax.swing.JComboBox jCombo_Typecompte1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_Gestion_compte;
    private javax.swing.JPanel jPanel_Liste;
    private javax.swing.JPanel jPanel_NouveauCompte;
    private javax.swing.JPanel jPanel_Releve;
    private javax.swing.JPanel jPanel_compte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Compte;
    private javax.swing.JTable jTable_Compte_releve;
    private javax.swing.JTextField nom_client;
    private javax.swing.JTextField num_compte;
    private javax.swing.JTextField solde_compte_gest;
    private javax.swing.JTextField taux_inter;
    // End of variables declaration//GEN-END:variables
}
